# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95ba7f4d76a36c93c5203039e244111ac944ed8dd6fb3da1ffacaeb650cdd997405422b60d42c723ee494c845719e69623833f1f82c2001e4166486d8733025

test:
  secret_key_base: 7eefed3cadb42dc97edebee4c4f6fcdd2419fe60fcf27866ffe9f09e8c9312370507984e463d2ccd5b50ff5fc14f39b2d4d1c25d57f4c969fb9369bb8cd5461b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
